config/routes.rb
Rails.application.routes.draw do
  root 'homes#index'

  devise_for :users
  as :user do
    get "signin" => "devise/sessions#new"
    post "signin" => "devise/sessions#create"
    delete "signout" => "devise/sessions#destroy"
  end

  devise_for :admins
  namespace :admin do
    root "dash_board#index"
    resources :categories
    resources :tables
    resources :dishes
  end
  resources :tables
  resources :categories
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :rememberable, :validatable
  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
            format: { with: VALID_EMAIL_REGEX },
            uniqueness: { case_sensitive: false }
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question

  has_many :user_answers, dependent: :destroy
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :dishes, dependent: :destroy
  validates :name, presence: true, length: { maximum: 100 }
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :dish
end

app/models/dish.rb
class Dish < ApplicationRecord
  has_many :order_dishes, dependent: :destroy
  has_many :comments, dependent: :destroy

  belongs_to :category

  has_one_attached :image

  validates :name, presence: true, length: { maximum: 50 }
  validates :content, presence: true, length: { maximum: 5000 }

  def display_image
    image.variant(resize_to_limit: [80, 90])
  end
end

app/models/feedback.rb
class Feedback < ApplicationRecord
  belongs_to :user

  has_many :user_answers, dependent: :destroy
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user

  has_many :order_dishes, dependent: :destroy
  has_many :order_tables, dependent: :destroy
end

app/models/order_dish.rb
class OrderDish < ApplicationRecord
  belongs_to :order
  belongs_to :dish
end

app/models/order_table.rb
class OrderTable < ApplicationRecord
  belongs_to :table
  belongs_to :order
end

app/models/question.rb
class Question < ApplicationRecord
  has_many :answers, dependent: :destroy
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
end

app/models/table.rb
class Table < ApplicationRecord
  has_many :order_tables
  validates :name, presence: true, length: { maximum: 30 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :orders, dependent: :destroy
  has_many :reviews, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :feedbacks, dependent: :destroy
end

app/models/user_answer.rb
class UserAnswer < ApplicationRecord
  belongs_to :feedback
  belongs_to :answer
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < Admin::AdminsController
  before_action :find_category , only: [:edit, :update, :destroy]
  def new
    @category = Category.new
  end

  def create
    @category = Category.new category_params
    if @category.save
      flash[:success] = "Tạo thành công"
      redirect_to admin_categories_path
    else
      render 'new'
    end
  end

  def index
    @categories = Category.paginate(page: params[:page])
  end

  def edit
  end

  def update
    if @category.update(category_params)
      flash[:success] = "Cập nhật danh mục"
      redirect_to admin_categories_path
    else
      render 'edit'
    end
  end

  def destroy
    @category.destroy
    flash[:success] = "Xoá danh mục"
    redirect_to admin_categories_path
  end

  private
  def find_category
    @category = Category.find_by(id: params[:id])
    redirect_to admin_categories_path unless @category
  end

  def category_params
    params.require(:category).permit(:name)
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = Category.all
    @dishes = Dish.all
  end
end

app/controllers/dishes_controller.rb
class DishesController < ApplicationController
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def index
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
end

app/controllers/tables_controller.rb
class TablesController < ApplicationController
  def index
    @tables = Table.all
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/categories/edit.html.erb
<h1 class="text-color">Cập nhật danh mục</h1>
<div class="row">
  <div class="col-md-6 offset-3">
    <%= form_for([:admin, @category]) do |f| %>

      <%= f.label "Tên", class: 'text-color' %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.submit "Cập nhật", class: "btn btn-primary mb-5 mt-3" %>
      <% end %>
  </div>
</div>

app/views/admin/categories/index.html.erb
<h1 class="text-color">Tất cả danh mục</h1>
<%= will_paginate %>
  <div>
    <p><%= link_to "Tạo danh mục", new_admin_category_path, class: 'text-color'%></p>
  </div>
  <table class="table table-bordered">
    <thead>
      <tr>
        <th>STT</th>
        <th>Tên</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <% @categories.each_with_index do |category, index| %>
        <tr>
          <td><%= index + 1 %></td>
          <td><%= link_to category.name, edit_admin_category_path(category),class: 'text-color' %></td>
          <td><%= link_to "Xoá", [:admin, category], method: :delete, class: 'text-color',
                                          data: { confirm: "Bạn có muốn xoá không?" } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<%= will_paginate %>

app/views/admin/categories/new.html.erb
<div class="col-md-6 offset-3">
  <%= form_for([:admin, @category]) do |f| %>

    <%= f.label "Tên", class: 'text-color' %>
    <%= f.text_field :name, class: 'form-control mt-2' %>

    <%= f.submit "Tạo mới danh mục", class: "btn btn-primary mb-5 mt-3" %>
  <% end %>
</div>

app/views/categories/index.html.erb
<section id="menu" class="menu section-bg" style="margin-top: 110px;">
  <div class="container" data-aos="fade-up">
    <div class="section-title">
      <h2>Thực đơn</h2>
      <p>Thực đơn của nhà hàng chúng tôi</p>
    </div>
    <ul class="nav nav-pills ha-menu mb-3" id="pills-tab" role="tablist" style="justify-content: center;">
      <% @categories.each_with_index do |category, i| %>
        <% class_name = i == 0 ? "nav-link active" : "nav-link" %>
        <li class="nav-item" role="presentation">
          <button class="<%= class_name %>" data-bs-toggle="pill" data-bs-target="#pills-<%= category.id %>" type="button" role="tab"><%= category.name %></button>
        </li>
      <% end %>
    </ul>
    <div class="tab-content" id="pills-tabContent">
      <% @categories.each_with_index do |category, j| %>
        <% class_name_div = j == 0 ? "tab-pane fade show active" : "tab-pane fade" %>
        <div class="<%= class_name_div %>" id="pills-<%= category.id %>" role="tabpanel" aria-labelledby="pills-home-tab">
          <div class="container">
            <div class="row menu-container">
              <% category.dishes.each do |dish| %>
                <div class="col-lg-6 menu-item">
                  <% image_path = dish.image.attached? ? dish.display_image : "default_dish_image.png" %>
                  <%= image_tag image_path , class:"menu-img" %>
                  <div class="menu-content">
                    <%= link_to dish.name, "#" %><span><%= dish.price %> VNĐ</span>
                  </div>
                  <div class="menu-ingredients">
                    <%= dish.content %>
                  </div>
                </div>
              <% end %>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</section><!-- End Menu Section -->