config/routes.rb
Rails.application.routes.draw do
  root 'homes#index'

  devise_for :users
  as :user do
    get "signin" => "devise/sessions#new"
    post "signin" => "devise/sessions#create"
    delete "signout" => "devise/sessions#destroy"
  end

  devise_for :admins
  namespace :admin do
    root "dash_board#index"
    resources :categories
    resources :tables
    resources :dishes
  end
  resources :tables
  resources :categories
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :rememberable, :validatable
  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
            format: { with: VALID_EMAIL_REGEX },
            uniqueness: { case_sensitive: false }
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question

  has_many :user_answers, dependent: :destroy
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :dishes, dependent: :destroy
  validates :name, presence: true, length: { maximum: 100 }
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :dish
end

app/models/dish.rb
class Dish < ApplicationRecord
  has_many :order_dishes, dependent: :destroy
  has_many :comments, dependent: :destroy

  belongs_to :category

  has_one_attached :image

  validates :name, presence: true, length: { maximum: 50 }
  validates :content, presence: true, length: { maximum: 5000 }

  def display_image
    image.variant(resize_to_limit: [80, 90])
  end
end

app/models/feedback.rb
class Feedback < ApplicationRecord
  belongs_to :user

  has_many :user_answers, dependent: :destroy
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user

  has_many :order_dishes, dependent: :destroy
  has_many :order_tables, dependent: :destroy
end

app/models/order_dish.rb
class OrderDish < ApplicationRecord
  belongs_to :order
  belongs_to :dish
end

app/models/order_table.rb
class OrderTable < ApplicationRecord
  belongs_to :table
  belongs_to :order
end

app/models/question.rb
class Question < ApplicationRecord
  has_many :answers, dependent: :destroy
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
end

app/models/table.rb
class Table < ApplicationRecord
  has_many :order_tables
  validates :name, presence: true, length: { maximum: 30 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :orders, dependent: :destroy
  has_many :reviews, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :feedbacks, dependent: :destroy
end

app/models/user_answer.rb
class UserAnswer < ApplicationRecord
  belongs_to :feedback
  belongs_to :answer
end

app/controllers/admin/tables_controller.rb
class Admin::TablesController < Admin::AdminsController
  before_action :find_table , only: [:edit, :update, :destroy]
  def new
    @table = Table.new
  end

  def create
    @table = Table.new table_params
    if @table.save
      flash[:success] = "Tạo thành công"
      redirect_to admin_tables_path
    else
      render 'new'
    end
  end

  def index
    @tables = Table.paginate(page: params[:page])
  end

  def edit
  end

  def update
    if @table.update(table_params)
      flash[:success] = "Cập nhật bàn "
      redirect_to admin_tables_path
    else
      render 'edit'
    end
  end

  def destroy
    @table.destroy
    flash[:success] = "Xoá bàn"
    redirect_to admin_tables_path
  end

  private
  def find_table
    @table = Table.find_by(id: params[:id])
    redirect_to admin_tables_path unless @table
  end

  def table_params
    params.require(:table).permit(:name)
  end
end

app/controllers/dishes_controller.rb
class DishesController < ApplicationController
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def index
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
end

app/controllers/tables_controller.rb
class TablesController < ApplicationController
  def index
    @tables = Table.all
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/tables/edit.html.erb
<h1 class="text-color">Cập nhật bàn</h1>
<div class="row">
  <div class="col-md-6 offset-3">
    <%= form_for([:admin, @table]) do |f| %>

      <%= f.label "Tên", class: 'text-color' %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.submit "Cập nhật", class: "btn btn-primary mb-5 mt-3" %>
      <% end %>
  </div>
</div>

app/views/admin/tables/index.html.erb
<h1 class="text-color">Danh sách bàn</h1>
<%= will_paginate %>
  <div>
    <p><%= link_to "Tạo mới", new_admin_table_path, class: 'text-color'%></p>
  </div>
  <table class="table table-bordered">
    <thead>
      <tr>
        <th>STT</th>
        <th>Tên</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <% @tables.each_with_index do |table, index| %>
        <tr>
          <td><%= index + 1 %></td>
          <td><%= link_to table.name, edit_admin_table_path(table),class: 'text-color' %></td>
          <td><%= link_to "Xoá", [:admin, table], method: :delete, class: 'text-color',
                                          data: { confirm: "Bạn có muốn xoá không?" } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<%= will_paginate %>

app/views/admin/tables/new.html.erb
<div class="col-md-6 offset-3">
  <%= form_for([:admin, @table]) do |f| %>

    <%= f.label "Tên", class: 'text-color' %>
    <%= f.text_field :name, class: 'form-control mt-2' %>

    <%= f.submit "Tạo bàn mới", class: "btn btn-primary mb-5 mt-3" %>
  <% end %>
</div>

app/views/tables/index.html.erb
<div class="booking-table">
  <div style="text-align: center; color: #cda45e;">
    <h1>Danh sách bàn</h1>
  </div>
  <div class="container">
    <div class="row">
    <% @tables.each do |table| %>
      <div id="icon-fork-knife-solid" class="wrap-icon with-top-tag col-2 mt-4">
        <button class="icon subtle" style="height: 100px; width: 100%; color: #fff; background: forestgreen;" data-bs-toggle="modal" data-bs-target="#exampleModal">
          <div>
            <i class="fa-solid fa-utensils" style="font-size: 30px;
            color: white;"></i>
          </div>
          <span class="icon-name"><%= table.name %></span>
        </button>
      </div>
    <% end %>
    </div>
  </div>
</div>
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title color-text" id="exampleModalLabel">Điền thông tin đặt bàn</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
          <div class="mb-3">
            <label for="recipient-name" class="col-form-label color-text">Recipient:</label>
            <input type="text" class="form-control" id="recipient-name">
          </div>
          <div class="mb-3">
            <label for="message-text" class="col-form-label color-text">Message:</label>
            <textarea class="form-control" id="message-text"></textarea>
          </div>
        </form>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Đóng</button>
        <button type="button" class="btn btn-primary">Send message</button>
      </div>
    </div>
  </div>
</div>